--- 
web:
  image: wordpress
  links: 
    - mysql:mysql
  ports: 
    - "80:80"
  volumes_from: 
    - paasdata

mysql:
  environment:
    - MYSQL_ROOT_PASSWORD=pass
  image: mysql
  volumes_from: 
    - paasdata

paasdata:
  image: busybox
  volumes:
    - /var/www/html/wp-content
    - /var/lib/mysql
  tty: true  
    

