version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password#
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password#
      MYSQL_DATABASE: my_db
  web:
      depends_on:
        - db
      build: .
      command: bash -c "/django/config.sh . venv/bin/activate && python /django/main/src/manage.py syncdb --noinput && python /django/main/src/manage.py migrate && python /django/main/src/manage.py populate_data && python /django/main/src/manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./:/django
      ports:
        - "8000:8000"
      expose:
        - "8000"  
      tty: true
      links:
        - db
